### PR TITLE
Add option to advise clients to disable code review requests.

### PR DESCRIPTION
**Pull request by jamox**

### CODE REVIEW

**Comment by josalmi** [comment]
Connects to #191

**Comment by jamox** [comment]
Should this default to false as described in #191?

**Comment by mpartel** [comment]
I think so.

Note that the migration should first default it to true to set it to true on all existing exercises and then change the default to false.

LGTM otherwise.

**Comment by jamox** [comment]
Updated migration. Set default value to false and update all existing records to have value true.

**Comment by mpartel** [comment]
Feel free to merge after addressing the above two comments.

**Pull request merged**
