### PR TITLE
Add the cookie consent banner as required by the EU

### PR DESCRIPTION
**Pull request by jamox**
WIP - RFC
eu

### CODE REVIEW

**Comment by jamox** [comment]
@mpartel Please review -- I chose the http://cookiepedia.co.uk/ for the more info as it seems to be nicely treating the cookie consent thingy.

Also about the message - now it is pretty much the least amount of text as possible - should we maybe elaborate on this.

**Comment by mpartel** [comment]
I think this is not necessary. http://ec.europa.eu/ipg/basics/legal/cookies/index_en.htm says e.g. "authentication cookies, to identify the user once he has logged in, for the duration of a session" are exempt from the requirement.

It will become necessary if we ever add analytics cookies or such.

**Comment by mpartel** [comment]
I think the above is only sure* to apply when the login cookie is non-persistent, which ours is.

[*] this stuff is infuriatingly vague

**Comment by jamox** [comment]
Closed as this turns out to be irrelevant. But kept safe should we ever add more tracking.

**Pull request closed without merging**
